# List all videos
GET http://localhost:3333/videos

###

# Get one video
GET http://localhost:3333/videos/(id)

###

# Create a video
POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Learn node today!",
  "description": "This is the year you will certainly leearn Node!",
  "duration": 507
}

###

# Update a video
PUT http://localhost:3333/videos/(id)
Content-Type: application/json

{
  "title": "The best emulators of 2024"
}

###

# Delete a video
DELETE http://localhost:3333/videos/(id)

###

# Populate database
POST http://localhost:3333/populate


